import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import SupabaseAuthListener from "@/components/auth/auth-listener";
import AuthModal from "@/components/auth/auth-modal";
import UserMenu from "@/components/auth/user-menu";
import { createClient } from "@/utils/supabase/server";
import { Suspense } from "react";
import AuthController from "@/components/auth/auth-controller";
import ImpersonateBanner from "./admin/users/_components/impersonate-banner";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import NotificationsListener from "@/components/notifications/notifications-listener";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-geist-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <head>
        {/* rest of your scripts go under */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} antialiased`}
      >
        <SupabaseAuthListener />
        <AuthController />
        <Toaster position="bottom-right" richColors />
        <NotificationsListener />
        <SidebarProvider>
          <AppSidebar user={user} />
          <SidebarInset>
            <header className="flex h-16 max-w-full shrink-0 items-center justify-between gap-2 border-b px-4">
              <SidebarTrigger className="-ml-1" />
              <div className="flex items-center justify-between">
                <ImpersonateBanner />
                <Suspense>
                  <UserMenu email={user?.email} />
                </Suspense>
              </div>
            </header>
            <main className="flex flex-1 flex-col gap-4 p-4">{children}</main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
